# Generated by Django 2.1.5 on 2019-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField()),
                ('Cname', models.CharField(max_length=100)),
                ('Cgen', models.CharField(max_length=5)),
                ('Cadd', models.CharField(max_length=100)),
            ],
        ),
    ]
